/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.ventanas;

/**
 *
 * @author leyv4a
 */
public class FrmMain extends javax.swing.JFrame {
//        pnlMain panelInicio = new pnlMain();

    /**
     * Creates new form main
     */
    public FrmMain() {
        initComponents();
        pnlPlacas.setVisible(false);
        pnlLicencia.setVisible(false);

        pnlResultadoConsulta.setVisible(false);
        pnlResultadoReportes.setVisible(false);
        pnlResultadoFiltro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        btnPlacas = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnLicencia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        pnlInicio = new javax.swing.JPanel();
        pnlModulosContainer = new javax.swing.JPanel();
        pnlConsultas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCurp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        btnBuscarCurp = new javax.swing.JButton();
        btnBuscarNombre = new javax.swing.JButton();
        btnBuscarFecha = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        pnlReportes = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFecha1 = new javax.swing.JTextField();
        btnGenerarPTiempo = new javax.swing.JButton();
        txtFecha2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbxTramite = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        btnGenerarTramite = new javax.swing.JButton();
        txtApellidoPReporte = new javax.swing.JTextField();
        btnGenerarNombre = new javax.swing.JButton();
        txtNombreReporte = new javax.swing.JTextField();
        txtApellidoMReporte = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pnlLogo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlResultadoConsulta = new javax.swing.JPanel();
        pnlResultadoFiltro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlResultadoReportes = new javax.swing.JPanel();
        pnlLicencia = new javax.swing.JPanel();
        pnlPlacas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setMaximumSize(new java.awt.Dimension(1440, 800));
        setMinimumSize(new java.awt.Dimension(1440, 800));
        setPreferredSize(new java.awt.Dimension(1440, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(217, 217, 217));
        pnlHeader.setMaximumSize(new java.awt.Dimension(1440, 90));
        pnlHeader.setMinimumSize(new java.awt.Dimension(1440, 90));
        pnlHeader.setPreferredSize(new java.awt.Dimension(1440, 90));

        btnPlacas.setBackground(new java.awt.Color(242, 242, 242));
        btnPlacas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPlacas.setForeground(new java.awt.Color(17, 17, 17));
        btnPlacas.setText("Placas");
        btnPlacas.setBorder(null);
        btnPlacas.setFocusable(false);
        btnPlacas.setMaximumSize(new java.awt.Dimension(133, 80));
        btnPlacas.setMinimumSize(new java.awt.Dimension(133, 80));
        btnPlacas.setPreferredSize(new java.awt.Dimension(133, 80));
        btnPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacasActionPerformed(evt);
            }
        });

        btnInicio.setBackground(new java.awt.Color(242, 242, 242));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(17, 17, 17));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.setFocusable(false);
        btnInicio.setMaximumSize(new java.awt.Dimension(133, 80));
        btnInicio.setMinimumSize(new java.awt.Dimension(133, 80));
        btnInicio.setPreferredSize(new java.awt.Dimension(133, 80));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnLicencia.setBackground(new java.awt.Color(242, 242, 242));
        btnLicencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLicencia.setForeground(new java.awt.Color(17, 17, 17));
        btnLicencia.setText("Licencia");
        btnLicencia.setBorder(null);
        btnLicencia.setFocusable(false);
        btnLicencia.setMaximumSize(new java.awt.Dimension(133, 80));
        btnLicencia.setMinimumSize(new java.awt.Dimension(133, 80));
        btnLicencia.setPreferredSize(new java.awt.Dimension(133, 80));
        btnLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicenciaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(150, 14, 83));
        jLabel1.setText("Sistema de Control de Placas y Licencias");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(4, Short.MAX_VALUE))
        );

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlMain.setBackground(new java.awt.Color(150, 14, 83));
        pnlMain.setMaximumSize(new java.awt.Dimension(1440, 710));
        pnlMain.setMinimumSize(new java.awt.Dimension(1440, 710));
        pnlMain.setPreferredSize(new java.awt.Dimension(1440, 710));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlInicio.setBackground(new java.awt.Color(150, 14, 83));
        pnlInicio.setMaximumSize(new java.awt.Dimension(1440, 710));
        pnlInicio.setMinimumSize(new java.awt.Dimension(1440, 710));
        pnlInicio.setPreferredSize(new java.awt.Dimension(1440, 710));
        pnlInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlModulosContainer.setMaximumSize(new java.awt.Dimension(430, 660));
        pnlModulosContainer.setMinimumSize(new java.awt.Dimension(430, 660));
        pnlModulosContainer.setPreferredSize(new java.awt.Dimension(430, 660));
        pnlModulosContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlConsultas.setBackground(new java.awt.Color(144, 14, 83));
        pnlConsultas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlConsultas.setMaximumSize(new java.awt.Dimension(430, 330));
        pnlConsultas.setMinimumSize(new java.awt.Dimension(430, 330));
        pnlConsultas.setPreferredSize(new java.awt.Dimension(430, 330));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("MODULO DE CONSULTAS");

        jLabel5.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel5.setText("Buscar historial de licencias y placas");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("CURP");

        txtNombre.setBackground(new java.awt.Color(242, 242, 242));
        txtNombre.setForeground(new java.awt.Color(1, 17, 17));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nombre");

        txtCurp.setBackground(new java.awt.Color(242, 242, 242));
        txtCurp.setForeground(new java.awt.Color(1, 17, 17));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Apellido M");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Apellido P");

        txtApellidoP.setBackground(new java.awt.Color(242, 242, 242));
        txtApellidoP.setForeground(new java.awt.Color(1, 17, 17));

        txtApellidoM.setBackground(new java.awt.Color(242, 242, 242));
        txtApellidoM.setForeground(new java.awt.Color(1, 17, 17));

        btnBuscarCurp.setBackground(new java.awt.Color(242, 242, 242));
        btnBuscarCurp.setForeground(new java.awt.Color(17, 17, 17));
        btnBuscarCurp.setText("BUSCAR");
        btnBuscarCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCurpActionPerformed(evt);
            }
        });

        btnBuscarNombre.setBackground(new java.awt.Color(242, 242, 242));
        btnBuscarNombre.setForeground(new java.awt.Color(17, 17, 17));
        btnBuscarNombre.setText("BUSCAR");
        btnBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreActionPerformed(evt);
            }
        });

        btnBuscarFecha.setBackground(new java.awt.Color(242, 242, 242));
        btnBuscarFecha.setForeground(new java.awt.Color(17, 17, 17));
        btnBuscarFecha.setText("BUSCAR");
        btnBuscarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFechaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("FECHA DE NACIMIENTO");

        jComboBox1.setBackground(new java.awt.Color(242, 242, 242));
        jComboBox1.setForeground(new java.awt.Color(17, 17, 17));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setBackground(new java.awt.Color(242, 242, 242));
        jComboBox2.setForeground(new java.awt.Color(17, 17, 17));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setBackground(new java.awt.Color(242, 242, 242));
        jComboBox3.setForeground(new java.awt.Color(17, 17, 17));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlConsultasLayout = new javax.swing.GroupLayout(pnlConsultas);
        pnlConsultas.setLayout(pnlConsultasLayout);
        pnlConsultasLayout.setHorizontalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasLayout.createSequentialGroup()
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultasLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCurp)
                                .addComponent(btnBuscarCurp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlConsultasLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8))
                                .addGroup(pnlConsultasLayout.createSequentialGroup()
                                    .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnBuscarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultasLayout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addGap(82, 82, 82))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultasLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnBuscarFecha))
                        .addGroup(pnlConsultasLayout.createSequentialGroup()
                            .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlConsultasLayout.createSequentialGroup()
                                    .addGap(101, 101, 101)
                                    .addComponent(jLabel4))
                                .addGroup(pnlConsultasLayout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGroup(pnlConsultasLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlConsultasLayout.setVerticalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(btnBuscarCurp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarFecha)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlModulosContainer.add(pnlConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 310));

        pnlReportes.setBackground(new java.awt.Color(144, 14, 83));
        pnlReportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlReportes.setMaximumSize(new java.awt.Dimension(430, 330));
        pnlReportes.setMinimumSize(new java.awt.Dimension(430, 330));
        pnlReportes.setPreferredSize(new java.awt.Dimension(430, 330));

        jLabel11.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel11.setText("Generar reporte de trámites realizados");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("MODULO DE REPORTES");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("PERIODO DE TIEMPO");

        txtFecha1.setBackground(new java.awt.Color(242, 242, 242));
        txtFecha1.setForeground(new java.awt.Color(1, 17, 17));

        btnGenerarPTiempo.setBackground(new java.awt.Color(242, 242, 242));
        btnGenerarPTiempo.setForeground(new java.awt.Color(17, 17, 17));
        btnGenerarPTiempo.setText("GENERAR");
        btnGenerarPTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPTiempoActionPerformed(evt);
            }
        });

        txtFecha2.setBackground(new java.awt.Color(242, 242, 242));
        txtFecha2.setForeground(new java.awt.Color(1, 17, 17));

        jLabel14.setText("Fecha 1(01/01/2001)");

        jLabel15.setText("Fecha 2(02/02/2002)");

        cbxTramite.setBackground(new java.awt.Color(242, 242, 242));
        cbxTramite.setForeground(new java.awt.Color(17, 17, 17));
        cbxTramite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tramite de placas", "Tramite de licencia" }));
        cbxTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTramiteActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("TIPO DE TRAMITE");

        btnGenerarTramite.setBackground(new java.awt.Color(242, 242, 242));
        btnGenerarTramite.setForeground(new java.awt.Color(17, 17, 17));
        btnGenerarTramite.setText("GENERAR");
        btnGenerarTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarTramiteActionPerformed(evt);
            }
        });

        txtApellidoPReporte.setBackground(new java.awt.Color(242, 242, 242));
        txtApellidoPReporte.setForeground(new java.awt.Color(1, 17, 17));

        btnGenerarNombre.setBackground(new java.awt.Color(242, 242, 242));
        btnGenerarNombre.setForeground(new java.awt.Color(17, 17, 17));
        btnGenerarNombre.setText("GENERAR");
        btnGenerarNombre.setMaximumSize(new java.awt.Dimension(86, 56));
        btnGenerarNombre.setMinimumSize(new java.awt.Dimension(86, 56));
        btnGenerarNombre.setPreferredSize(new java.awt.Dimension(86, 56));
        btnGenerarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarNombreActionPerformed(evt);
            }
        });

        txtNombreReporte.setBackground(new java.awt.Color(242, 242, 242));
        txtNombreReporte.setForeground(new java.awt.Color(1, 17, 17));

        txtApellidoMReporte.setBackground(new java.awt.Color(242, 242, 242));
        txtApellidoMReporte.setForeground(new java.awt.Color(1, 17, 17));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Nombre(s)");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Apellido M");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Apellido P");

        javax.swing.GroupLayout pnlReportesLayout = new javax.swing.GroupLayout(pnlReportes);
        pnlReportes.setLayout(pnlReportesLayout);
        pnlReportesLayout.setHorizontalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportesLayout.createSequentialGroup()
                .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReportesLayout.createSequentialGroup()
                        .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlReportesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlReportesLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel14)))
                        .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlReportesLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGenerarPTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlReportesLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel15)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlReportesLayout.createSequentialGroup()
                        .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlReportesLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel12))
                            .addGroup(pnlReportesLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlReportesLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel13))
                            .addGroup(pnlReportesLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel16)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlReportesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReportesLayout.createSequentialGroup()
                                .addComponent(cbxTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGenerarTramite, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlReportesLayout.createSequentialGroup()
                                .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReportesLayout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNombreReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReportesLayout.createSequentialGroup()
                                        .addComponent(txtApellidoPReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtApellidoMReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnGenerarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReportesLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addGap(127, 127, 127)))))
                .addContainerGap())
        );
        pnlReportesLayout.setVerticalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(4, 4, 4)
                .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGenerarPTiempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(20, 20, 20)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTramite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarTramite))
                .addGap(18, 18, 18)
                .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReportesLayout.createSequentialGroup()
                        .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidoPReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoMReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnGenerarNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pnlModulosContainer.add(pnlReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, 400));

        pnlInicio.add(pnlModulosContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 710));

        pnlLogo.setBackground(new java.awt.Color(150, 14, 83));
        pnlLogo.setMaximumSize(new java.awt.Dimension(1010, 710));
        pnlLogo.setMinimumSize(new java.awt.Dimension(1010, 710));
        pnlLogo.setPreferredSize(new java.awt.Dimension(1010, 710));

        jLabel3.setText("IMAGEN LOGO SONORA");

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoLayout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pnlInicio.add(pnlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 0, -1, -1));

        pnlResultadoConsulta.setBackground(new java.awt.Color(0, 255, 0));
        pnlResultadoConsulta.setMaximumSize(new java.awt.Dimension(1010, 710));
        pnlResultadoConsulta.setMinimumSize(new java.awt.Dimension(1010, 710));
        pnlResultadoConsulta.setPreferredSize(new java.awt.Dimension(1010, 710));

        javax.swing.GroupLayout pnlResultadoConsultaLayout = new javax.swing.GroupLayout(pnlResultadoConsulta);
        pnlResultadoConsulta.setLayout(pnlResultadoConsultaLayout);
        pnlResultadoConsultaLayout.setHorizontalGroup(
            pnlResultadoConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        pnlResultadoConsultaLayout.setVerticalGroup(
            pnlResultadoConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        pnlInicio.add(pnlResultadoConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 0, -1, -1));

        pnlResultadoFiltro.setBackground(new java.awt.Color(255, 153, 0));
        pnlResultadoFiltro.setMaximumSize(new java.awt.Dimension(1010, 710));
        pnlResultadoFiltro.setMinimumSize(new java.awt.Dimension(1010, 710));
        pnlResultadoFiltro.setPreferredSize(new java.awt.Dimension(1010, 710));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("Resultados de la busqueda");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Pancho lalalalalsda", "ASDASDA", " Seleccionar"}
            },
            new String [] {
                "Nombre", "CURP", "Accion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnlResultadoFiltroLayout = new javax.swing.GroupLayout(pnlResultadoFiltro);
        pnlResultadoFiltro.setLayout(pnlResultadoFiltroLayout);
        pnlResultadoFiltroLayout.setHorizontalGroup(
            pnlResultadoFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadoFiltroLayout.createSequentialGroup()
                .addGroup(pnlResultadoFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlResultadoFiltroLayout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlResultadoFiltroLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        pnlResultadoFiltroLayout.setVerticalGroup(
            pnlResultadoFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadoFiltroLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pnlInicio.add(pnlResultadoFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 0, -1, -1));

        pnlResultadoReportes.setBackground(new java.awt.Color(255, 153, 153));
        pnlResultadoReportes.setMaximumSize(new java.awt.Dimension(1010, 710));
        pnlResultadoReportes.setMinimumSize(new java.awt.Dimension(1010, 710));
        pnlResultadoReportes.setPreferredSize(new java.awt.Dimension(1010, 710));

        javax.swing.GroupLayout pnlResultadoReportesLayout = new javax.swing.GroupLayout(pnlResultadoReportes);
        pnlResultadoReportes.setLayout(pnlResultadoReportesLayout);
        pnlResultadoReportesLayout.setHorizontalGroup(
            pnlResultadoReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        pnlResultadoReportesLayout.setVerticalGroup(
            pnlResultadoReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        pnlInicio.add(pnlResultadoReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 0, -1, -1));

        pnlMain.add(pnlInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlLicencia.setBackground(new java.awt.Color(153, 153, 255));
        pnlLicencia.setMaximumSize(new java.awt.Dimension(1440, 710));
        pnlLicencia.setMinimumSize(new java.awt.Dimension(1440, 710));
        pnlLicencia.setPreferredSize(new java.awt.Dimension(1440, 710));

        javax.swing.GroupLayout pnlLicenciaLayout = new javax.swing.GroupLayout(pnlLicencia);
        pnlLicencia.setLayout(pnlLicenciaLayout);
        pnlLicenciaLayout.setHorizontalGroup(
            pnlLicenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlLicenciaLayout.setVerticalGroup(
            pnlLicenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlMain.add(pnlLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlPlacas.setBackground(new java.awt.Color(0, 153, 153));
        pnlPlacas.setMaximumSize(new java.awt.Dimension(1440, 710));
        pnlPlacas.setMinimumSize(new java.awt.Dimension(1440, 710));
        pnlPlacas.setPreferredSize(new java.awt.Dimension(1440, 710));

        javax.swing.GroupLayout pnlPlacasLayout = new javax.swing.GroupLayout(pnlPlacas);
        pnlPlacas.setLayout(pnlPlacasLayout);
        pnlPlacasLayout.setHorizontalGroup(
            pnlPlacasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlPlacasLayout.setVerticalGroup(
            pnlPlacasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlMain.add(pnlPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        pnlInicio.setVisible(true);
        pnlLicencia.setVisible(false);
        pnlPlacas.setVisible(false);
        pnlLogo.setVisible(true);
        pnlResultadoFiltro.setVisible(false);
        pnlResultadoConsulta.setVisible(false);
        pnlResultadoReportes.setVisible(false);
             


    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacasActionPerformed
        pnlInicio.setVisible(false);
        pnlLicencia.setVisible(false);
        pnlPlacas.setVisible(true);
    }//GEN-LAST:event_btnPlacasActionPerformed

    private void btnLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicenciaActionPerformed
        pnlInicio.setVisible(false);
        pnlLicencia.setVisible(true);
        pnlPlacas.setVisible(false);
    }//GEN-LAST:event_btnLicenciaActionPerformed

    private void btnBuscarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFechaActionPerformed
        pnlLogo.setVisible(false);
        pnlResultadoFiltro.setVisible(true);
    }//GEN-LAST:event_btnBuscarFechaActionPerformed

    private void btnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreActionPerformed
        pnlLogo.setVisible(false);
        pnlResultadoFiltro.setVisible(true);
    }//GEN-LAST:event_btnBuscarNombreActionPerformed

    private void btnBuscarCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCurpActionPerformed
        pnlLogo.setVisible(false);
        pnlResultadoFiltro.setVisible(true);
    }//GEN-LAST:event_btnBuscarCurpActionPerformed

    private void btnGenerarPTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPTiempoActionPerformed
        pnlLogo.setVisible(false);
        pnlResultadoFiltro.setVisible(true);
    }//GEN-LAST:event_btnGenerarPTiempoActionPerformed

    private void btnGenerarTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarTramiteActionPerformed
        pnlLogo.setVisible(false);
        pnlResultadoFiltro.setVisible(true);
    }//GEN-LAST:event_btnGenerarTramiteActionPerformed

    private void cbxTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTramiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTramiteActionPerformed

    private void btnGenerarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarNombreActionPerformed
        pnlLogo.setVisible(false);
        pnlResultadoFiltro.setVisible(true);
    }//GEN-LAST:event_btnGenerarNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCurp;
    private javax.swing.JButton btnBuscarFecha;
    private javax.swing.JButton btnBuscarNombre;
    private javax.swing.JButton btnGenerarNombre;
    private javax.swing.JButton btnGenerarPTiempo;
    private javax.swing.JButton btnGenerarTramite;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLicencia;
    private javax.swing.JButton btnPlacas;
    private javax.swing.JComboBox<String> cbxTramite;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlConsultas;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlInicio;
    private javax.swing.JPanel pnlLicencia;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlModulosContainer;
    private javax.swing.JPanel pnlPlacas;
    private javax.swing.JPanel pnlReportes;
    private javax.swing.JPanel pnlResultadoConsulta;
    private javax.swing.JPanel pnlResultadoFiltro;
    private javax.swing.JPanel pnlResultadoReportes;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoMReporte;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtApellidoPReporte;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtFecha1;
    private javax.swing.JTextField txtFecha2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreReporte;
    // End of variables declaration//GEN-END:variables
}
